### PR TITLE
Adds sum of voxels (Integrated Density) to LabeledVoxelsMeasure

### PR DESCRIPTION
**Pull request by lacan**
The value was computed but not used, so this quick commit fixes that :)

### CODE REVIEW

**Comment by lacan** [comment]
Merci!

**Comment by dlegland** [comment]
you're welcome!
I have just reverted the development version back to 1.3.4 (in the POM)

**Comment by imagejan** [comment]
> I have just reverted the development version back to 1.3.4 (in the POM)

which is unfortunate because you now have a `MorphoLibJ-1.3.5-SNAPSHOT` on the Maven repository anyways:

http://maven.imagej.net/#nexus-search;quick~MorphoLibJ

(Though only temporary, until that one gets replaced by another 1.3.5-SNAPSHOT in the future.)

**Comment by imagejan** [comment]
@dlegland  wrote:
> I don't know where this snapshot comes from...

It was uploaded by the continuous integration at the moment the PR was merged; more precisely by this Travis CI job (that's accessible from the little green check mark next to each commit in the [commit view](https://github.com/ijpb/MorphoLibJ/commits/master)):

https://travis-ci.org/ijpb/MorphoLibJ/builds/362567621#L458

(Travis uploads SNAPSHOTs to the snapshots repository, and releases to the release repository of maven.imagej.net)

**Pull request merged**
