### PR TITLE
Re-activate continuous integration and jar deployment

### PR DESCRIPTION
**Pull request by imagejan**
* Migrate from travis to GitHub Actions (travis-ci.org have stopped their service).
* Deploy the built jar files to maven.scijava.org

In order to have jar files for every release version of MorphoLibJ deployed to https://maven.scijava.org (and therefore available to third-party projects depending on it), please:

* grant @ctrueden or @hinerm temporarily access (i.e. owner) on the `ijpb` organization, so they can add the SciJava secrets for deployment (if it didn't happen already),
* in the future, always use [`release-version.sh`](https://github.com/scijava/scijava-scripts/blob/main/release-version.sh) to cut a new release (i.e. no more double-push to master, and in general never manually push a release version), and
* stick to semantic versioning, i.e. three numbers: `major.minor.patch`

### CODE REVIEW

**Comment by iarganda** [comment]
@imagejan I have invited @hinerm and @ctrueden as "owners" (I hope you don't mind, @dlegland).

Shall I change the pre-release to use the semantic versioning?

**Comment by dlegland** [comment]
Hi,
I think that's ok for the time to solve the problem.

More generally, I appreciate the efforts made to make all the ImageJ/Fiji contributions working together; however, as it seems there are some rules or practices concerning the deployment of Fiji-related contributions, this would be convenient to have them summarized somewhere. If they are, maybe have a link in the PR message?

**Comment by ctrueden** [comment]
@iarganda wrote:
> I have invited @hinerm and @ctrueden as "owners"

I have now added the needed secrets to the ijpb repository. Any public repositories in this organization will now be able to deploy to maven.scijava.org via GitHub Actions CI.

@iarganda wrote:
> The errors come from the javadoc generation, so I believe they were skipped before?

I pushed a commit that fixes the doclint errors: d292f5284b06358d9a80df212226f22470242a75

@dlegland wrote:
> it seems there are some rules or practices concerning the deployment of Fiji-related contributions, this would be convenient to have them summarized somewhere.

For MorphoLibJ, there are no rules, because it has its own update site. However, there are guidelines, which if you follow, the update site will stay in better sync with Fiji as it evolves.

About release best practices:
* https://imagej.net/develop/releasing

About contributing a plugin to the Fiji distribution (in case MorphoLibJ ever wants to be included in Fiji):
* https://imagej.net/contribute/fiji

I also plan to write a document about becoming part of the pom-scijava Bill of Materials, which would benefit MorphoLibJ in that it would get it tested in the big "melting pot" of SciJava-based components, to catch library version incompatibilities sooner. But I haven't written that document yet, unfortunately.

**Comment by dlegland** [comment]
@ctrueden : that's great! thanks for fixing this! well, mea culpa, it seems I did not write comments the right way.... with the new systems I should be warned next time!

**Pull request merged**
