### PR TITLE
WIP Child Parent Merge

### PR DESCRIPTION
**Pull request by tischi**
@dlegland 
I added a class that can merge two results tables containing child and parent objects.
I don't expect you to merge it as is, but I thought this PR is a good way to remember that this is something that one could eventually add to MLJ and also to discuss how to do it best.

### CODE REVIEW

**Comment by dlegland** [comment]
Hi!
thanks for this. Yes, good idea to keep it as WIP!
I also have some code for working with results table that I should take time to finalize. I do not know however if the best is to integrate into MLJ or to create a dedicated package for management of tables with IJ.
Let's think about it anyway.

**Comment by tischi** [comment]
> I do not know however if the best is to integrate into MLJ or to create a dedicated package for management of tables with IJ.

I think separate package and maybe even separate update site could an idea such that other people can reuse it.

@haesleinhuepf, did you already decide on what you want to use for tabular output in CLIJ? Maybe also the good old `ResultsTable` or something else?

**Comment by haesleinhuepf** [comment]
> @haesleinhuepf, did you already decide on what you want to use for tabular output in CLIJ? Maybe also the good old `ResultsTable` or something else?

Not sure what you mean, but yes: CLIJ works with ij.measure.ResultsTable. Also not sure if there are any useful alternatives.

**Comment by tischi** [comment]
@haesleinhuepf 
Thanks!
The point was whether it could be worth having a common repo / Update Site for code and plugins related to manipulations on ResultsTables, rather than adding that to MLJ.

**Comment by haesleinhuepf** [comment]
> @haesleinhuepf
> Thanks!
> The point was whether it could be worth having a common repo / Update Site for code and plugins related to manipulations on ResultsTables, rather than adding that to MLJ.

Ah ok. Thanks for the clarification. Processing tables happens in CLIJ on the GPU. CLIJ just supports import/export of ij.measure.ResultsTable. If you plan to make a general package on processing tables, I would suggest putting it in gtihub.com/fiji and delivering it via the  Fiji update site. A separate update site might not be necessary ;-)

**Comment by tischi** [comment]
Hi @haesleinhuepf and @dlegland,
I need the functionality for merging child and parent tables soon for a course.
I think I will ship this _for now_ with this update site: https://github.com/tischi/segmentation-annotator#segmentation-annotator
But I think it would be nice to find some other home for ResultsTable manipulations.
Right now I however don't have the bandwidth to come up with a good solution...

**Comment by dlegland** [comment]
Hi, 
ok, do the best you can for the moment!

I was thinking about a "TableJ" plugin for a while, to expand ResultsTable possiblities. I think it could be also possible to have PCA or Anova features as well!
But I won't have time soon neither... maybe I can think again about it this summer.

cheers...

**Comment by tischi** [comment]
TableJ sounds awesome 🥳 
Looking forward to this 🤩

**Pull request closed without merging**
