### PR TITLE
Adding 2D watershed test

### PR DESCRIPTION
**Pull request by dmikushin**
Watershed transforms do not have tests in the test suite. This commit adds 2D watershed test case for both 4 and 8 connectivities and two reference images to check against.

Additional cosmetic optimizations/cleanups: the check for h <= hMax could also be dropped in the while loop condition. Then, "h" could be initialized in the body of while loop.

### CODE REVIEW

**Comment by dmikushin** [comment]
Hi @iarganda, thanks, I've made a cleanup according with your comments. I used input image also as a mask in order to maximize masking mode randomness, lacking any better idea. Could you please review once again?

**Comment by iarganda** [comment]
Hi @dmikushin, instead of using the input image as mask you can simply set it to `null`, so there is no limitation in the execution of the algorithm. Right now, using the grains image as mask the effect is the same because it does not have any pixel with zero intensity value.

**Comment by dmikushin** [comment]
I think it would be better for testing to have some actual mask instead of null. Please review commit 26d400074308d0663ea7e83c0b6dd3bd5edce77c: there a random mask is generated with simple xorshift, reference resulting images are updated accordingly.

**Comment by iarganda** [comment]
OK, now it looks better. Out of curiosity, why a random mask instead of no mask?
A few comments about the code:
* Lines 29, 31, 33, 35 and 36 contain unused imports.
* Line 58 contains a misleading javadoc comment.
* Apart from testing the connectivity values, why not checking as well if the results are the same using a 16-bit and 32-bit version of the input image as in the MorphologicalSegmentation test?

**Comment by dmikushin** [comment]
Right, thanks, could you please review the update?

**Pull request merged**
